// import bcryptjs from "bcryptjs";
import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "James",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Free Male Shirt",
      slug: "free-shirt2",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Not Free Shirt",
      slug: "free-shirt3",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fiona XL F Pants",
      slug: "free-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 70,
      brand: "Fiona",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Zara Pants",
      slug: "free-pants2",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 70,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Lorenza Male Pants",
      slug: "free-pants3",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 70,
      brand: "Lorenza",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
};
export default data;
